name: Smart Migration Script Runner

on:
  push:
    branches:
      - feature/metadataworkflow
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    concurrency:
      group: migration
      cancel-in-progress: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-gitlab PyGithub requests PyJWT python-dotenv openpyxl

      - name: Run Metadata Migration
        env:
          GITLABTOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running migration..."

          python scripts/repo/gitlab_metadata.py
          python scripts/repo/gitlab_to_github_metadata.py \
            --gitlab-token "${GITLABTOKEN}" \
            --github-token "${GITHUBTOKEN}" \
            --gitlab-project mygroup/myrepo \
            --github-org rohithmamidi \
            --github-repo gitlabtogithub

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migration-artifacts
          path: |
            *.csv
            *.log
            output/